/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistasNoticias;

/**
 *
 * @author Byron
 */
public class AgregarNews extends javax.swing.JPanel {

    /**
     * Creates new form AgregarNews
     */
    public AgregarNews() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAgregarNews = new javax.swing.JPanel();
        FieldURL = new javax.swing.JLabel();
        FieldDescripcion = new javax.swing.JLabel();
        PanelTitulo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Borde = new javax.swing.JPanel();
        FieldID = new javax.swing.JTextField();
        FieldPassNew = new javax.swing.JTextField();
        AgregarButton = new javax.swing.JButton();
        FieldTipoN = new javax.swing.JLabel();
        FielPassActual = new javax.swing.JTextField();
        FieldNID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextDescripcion = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(500, 377));
        setPreferredSize(new java.awt.Dimension(500, 377));

        PanelAgregarNews.setBackground(new java.awt.Color(201, 234, 253));
        PanelAgregarNews.setMinimumSize(new java.awt.Dimension(500, 377));
        PanelAgregarNews.setPreferredSize(new java.awt.Dimension(500, 377));
        PanelAgregarNews.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FieldURL.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        FieldURL.setForeground(new java.awt.Color(76, 168, 207));
        FieldURL.setText("URL:");
        FieldURL.setMaximumSize(new java.awt.Dimension(100, 40));
        FieldURL.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelAgregarNews.add(FieldURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        FieldDescripcion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        FieldDescripcion.setForeground(new java.awt.Color(76, 168, 207));
        FieldDescripcion.setText("Descripción:");
        FieldDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        FieldDescripcion.setMaximumSize(new java.awt.Dimension(100, 40));
        FieldDescripcion.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelAgregarNews.add(FieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, -1));

        PanelTitulo.setBackground(new java.awt.Color(76, 168, 207));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 51));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Agregar Noticia");

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        PanelAgregarNews.add(PanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 40));

        Borde.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout BordeLayout = new javax.swing.GroupLayout(Borde);
        Borde.setLayout(BordeLayout);
        BordeLayout.setHorizontalGroup(
            BordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        BordeLayout.setVerticalGroup(
            BordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        PanelAgregarNews.add(Borde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 510, 5));

        FieldID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldID.setBorder(null);
        FieldID.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldID.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldIDActionPerformed(evt);
            }
        });
        PanelAgregarNews.add(FieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 280, 30));

        FieldPassNew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldPassNew.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldPassNew.setBorder(null);
        FieldPassNew.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldPassNew.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldPassNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldPassNewActionPerformed(evt);
            }
        });
        PanelAgregarNews.add(FieldPassNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 170, 30));

        AgregarButton.setBackground(new java.awt.Color(76, 168, 207));
        AgregarButton.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        AgregarButton.setForeground(new java.awt.Color(255, 255, 255));
        AgregarButton.setText("Agregar");
        AgregarButton.setMaximumSize(new java.awt.Dimension(104, 40));
        AgregarButton.setPreferredSize(new java.awt.Dimension(104, 40));
        AgregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarButtonActionPerformed(evt);
            }
        });
        PanelAgregarNews.add(AgregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        FieldTipoN.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        FieldTipoN.setForeground(new java.awt.Color(76, 168, 207));
        FieldTipoN.setText("Tipo noticia");
        FieldTipoN.setMaximumSize(new java.awt.Dimension(100, 40));
        FieldTipoN.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelAgregarNews.add(FieldTipoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, -1));

        FielPassActual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FielPassActual.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FielPassActual.setBorder(null);
        FielPassActual.setMaximumSize(new java.awt.Dimension(140, 35));
        FielPassActual.setPreferredSize(new java.awt.Dimension(140, 35));
        FielPassActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FielPassActualActionPerformed(evt);
            }
        });
        PanelAgregarNews.add(FielPassActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 170, 30));

        FieldNID.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        FieldNID.setForeground(new java.awt.Color(76, 168, 207));
        FieldNID.setText("Numero identificador:");
        FieldNID.setMaximumSize(new java.awt.Dimension(100, 40));
        FieldNID.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelAgregarNews.add(FieldNID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, -1));

        TextDescripcion.setColumns(20);
        TextDescripcion.setRows(5);
        jScrollPane1.setViewportView(TextDescripcion);

        PanelAgregarNews.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 280, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelAgregarNews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelAgregarNews, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldIDActionPerformed

    private void FieldPassNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPassNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPassNewActionPerformed

    private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed
        /*
        VALIDAR QUE SE HAYAN INGRESADO BIEN LOS DATOS --> Funciones de la clase
        Mostrar showDialog
        */
    }//GEN-LAST:event_AgregarButtonActionPerformed

    private void FielPassActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FielPassActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FielPassActualActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarButton;
    private javax.swing.JPanel Borde;
    private javax.swing.JTextField FielPassActual;
    private javax.swing.JLabel FieldDescripcion;
    private javax.swing.JTextField FieldID;
    private javax.swing.JLabel FieldNID;
    private javax.swing.JTextField FieldPassNew;
    private javax.swing.JLabel FieldTipoN;
    private javax.swing.JLabel FieldURL;
    private javax.swing.JPanel PanelAgregarNews;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JTextArea TextDescripcion;
    private javax.swing.JLabel Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
