/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistasNoticias;

/**
 *
 * @author Byron
 */
public class EliminarNews extends javax.swing.JPanel {

    /**
     * Creates new form Eliminar
     */
    public EliminarNews() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEliminarNews = new javax.swing.JPanel();
        LabelID = new javax.swing.JLabel();
        PanelTitulo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Borde = new javax.swing.JPanel();
        FieldID = new javax.swing.JTextField();
        ELiminarButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(500, 377));
        setPreferredSize(new java.awt.Dimension(500, 377));

        PanelEliminarNews.setBackground(new java.awt.Color(201, 234, 253));
        PanelEliminarNews.setMaximumSize(new java.awt.Dimension(500, 377));
        PanelEliminarNews.setPreferredSize(new java.awt.Dimension(500, 377));
        PanelEliminarNews.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelID.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        LabelID.setForeground(new java.awt.Color(76, 168, 207));
        LabelID.setText("Identificador Noticia:");
        LabelID.setMaximumSize(new java.awt.Dimension(100, 40));
        LabelID.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelEliminarNews.add(LabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 170, -1));

        PanelTitulo.setBackground(new java.awt.Color(76, 168, 207));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 51));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Eliminar Noticia");

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        PanelEliminarNews.add(PanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        Borde.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout BordeLayout = new javax.swing.GroupLayout(Borde);
        Borde.setLayout(BordeLayout);
        BordeLayout.setHorizontalGroup(
            BordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        BordeLayout.setVerticalGroup(
            BordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        PanelEliminarNews.add(Borde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 500, 5));

        FieldID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldID.setBorder(null);
        FieldID.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldID.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldIDActionPerformed(evt);
            }
        });
        PanelEliminarNews.add(FieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, 30));

        ELiminarButton.setBackground(new java.awt.Color(76, 168, 207));
        ELiminarButton.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        ELiminarButton.setForeground(new java.awt.Color(255, 255, 255));
        ELiminarButton.setText("Eliminar");
        ELiminarButton.setMaximumSize(new java.awt.Dimension(104, 40));
        ELiminarButton.setPreferredSize(new java.awt.Dimension(104, 40));
        ELiminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELiminarButtonActionPerformed(evt);
            }
        });
        PanelEliminarNews.add(ELiminarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelEliminarNews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelEliminarNews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldIDActionPerformed

    private void ELiminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELiminarButtonActionPerformed
        /*
        VALIDAR QUE SE HAYAN INGRESADO BIEN LOS DATOS --> Funciones de la clase
        Mostrar showDialog
        */

    }//GEN-LAST:event_ELiminarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Borde;
    private javax.swing.JButton ELiminarButton;
    private javax.swing.JTextField FieldID;
    private javax.swing.JLabel LabelID;
    private javax.swing.JPanel PanelEliminarNews;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
