/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaMain;
import VistasAdministrador.AgregarAdmin;
import VistasAdministrador.CambiarPassword;
import VistasNoticias.*;
import VistasPuntosR.*;
import java.awt.BorderLayout;
import javax.swing.JPanel;

public class AdminFuncion extends javax.swing.JFrame {

    VentanaAdmin InicioAdmin = new VentanaAdmin();
    
    public AdminFuncion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContent = new javax.swing.JPanel();
        TituloPrincipal = new javax.swing.JLabel();
        MenuBarAdmin = new javax.swing.JMenuBar();
        MenuAdmin = new javax.swing.JMenu();
        ItemAgregar = new javax.swing.JMenuItem();
        ItemCambioPass = new javax.swing.JMenuItem();
        ItemSalir = new javax.swing.JMenuItem();
        MenuPR = new javax.swing.JMenu();
        ItemAgregarPR = new javax.swing.JMenuItem();
        ItemMostrar = new javax.swing.JMenuItem();
        ItemEliminarPR = new javax.swing.JMenuItem();
        ItemActualizarPR = new javax.swing.JMenuItem();
        MenuN = new javax.swing.JMenu();
        ItemAgregarN = new javax.swing.JMenuItem();
        ItemEliminarN = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FuncionesAdministrador");
        setResizable(false);

        PanelContent.setBackground(new java.awt.Color(102, 190, 230));
        PanelContent.setMaximumSize(new java.awt.Dimension(500, 377));

        TituloPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        TituloPrincipal.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        TituloPrincipal.setForeground(new java.awt.Color(0, 0, 102));
        TituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloPrincipal.setText("RecyPoint");
        TituloPrincipal.setAlignmentY(0.0F);
        TituloPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));

        javax.swing.GroupLayout PanelContentLayout = new javax.swing.GroupLayout(PanelContent);
        PanelContent.setLayout(PanelContentLayout);
        PanelContentLayout.setHorizontalGroup(
            PanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContentLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(TituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        PanelContentLayout.setVerticalGroup(
            PanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContentLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(TituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        MenuBarAdmin.setForeground(new java.awt.Color(0, 0, 102));

        MenuAdmin.setText("Administrador");

        ItemAgregar.setText("Agregar");
        ItemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAgregarActionPerformed(evt);
            }
        });
        MenuAdmin.add(ItemAgregar);

        ItemCambioPass.setText("Cambiar contraseña");
        ItemCambioPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCambioPassActionPerformed(evt);
            }
        });
        MenuAdmin.add(ItemCambioPass);

        ItemSalir.setText("Salir");
        ItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSalirActionPerformed(evt);
            }
        });
        MenuAdmin.add(ItemSalir);

        MenuBarAdmin.add(MenuAdmin);

        MenuPR.setText("Puntos de reciclaje");

        ItemAgregarPR.setText("Agregar");
        ItemAgregarPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAgregarPRActionPerformed(evt);
            }
        });
        MenuPR.add(ItemAgregarPR);

        ItemMostrar.setText("Mostrar puntos");
        ItemMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMostrarActionPerformed(evt);
            }
        });
        MenuPR.add(ItemMostrar);

        ItemEliminarPR.setText("Eliminar punto de reciclaje");
        ItemEliminarPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEliminarPRActionPerformed(evt);
            }
        });
        MenuPR.add(ItemEliminarPR);

        ItemActualizarPR.setText("Actualizar punto de reciclaje");
        ItemActualizarPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemActualizarPRActionPerformed(evt);
            }
        });
        MenuPR.add(ItemActualizarPR);

        MenuBarAdmin.add(MenuPR);

        MenuN.setText("Noticias");

        ItemAgregarN.setText("Agregar");
        ItemAgregarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAgregarNActionPerformed(evt);
            }
        });
        MenuN.add(ItemAgregarN);

        ItemEliminarN.setText("Eliminar noticia");
        ItemEliminarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEliminarNActionPerformed(evt);
            }
        });
        MenuN.add(ItemEliminarN);

        MenuBarAdmin.add(MenuN);

        setJMenuBar(MenuBarAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ItemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAgregarActionPerformed
        AgregarAdmin pagAgregar =  new AgregarAdmin();
        MostrarPanel(pagAgregar);
    }//GEN-LAST:event_ItemAgregarActionPerformed

    private void ItemMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemMostrarActionPerformed

    private void ItemCambioPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCambioPassActionPerformed
        CambiarPassword pagCambioP = new CambiarPassword();
        MostrarPanel(pagCambioP);
    }//GEN-LAST:event_ItemCambioPassActionPerformed

    private void ItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSalirActionPerformed
        InicioAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemSalirActionPerformed

    private void ItemAgregarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAgregarNActionPerformed
        AgregarNews pagAddNews = new AgregarNews();
        MostrarPanel(pagAddNews);
    }//GEN-LAST:event_ItemAgregarNActionPerformed

    private void ItemEliminarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEliminarNActionPerformed
        EliminarNews NewsEliminar = new EliminarNews();
        MostrarPanel(NewsEliminar);
    }//GEN-LAST:event_ItemEliminarNActionPerformed

    private void ItemAgregarPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAgregarPRActionPerformed
        AgregarAdmin addPR = new AgregarAdmin();
        MostrarPanel(addPR);
    }//GEN-LAST:event_ItemAgregarPRActionPerformed

    private void ItemEliminarPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEliminarPRActionPerformed
        EliminarPR deletePR = new EliminarPR();
        MostrarPanel(deletePR);
    }//GEN-LAST:event_ItemEliminarPRActionPerformed

    private void ItemActualizarPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemActualizarPRActionPerformed
        ActualizarPR UpdatePR = new ActualizarPR();
        MostrarPanel(UpdatePR);
    }//GEN-LAST:event_ItemActualizarPRActionPerformed

    private void MostrarPanel(JPanel p){
        p.setSize(500,377);
        p.setLocation(0,0);
        
        PanelContent.removeAll();
        PanelContent.add(p, BorderLayout.CENTER);
        PanelContent.revalidate();
        PanelContent.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemActualizarPR;
    private javax.swing.JMenuItem ItemAgregar;
    private javax.swing.JMenuItem ItemAgregarN;
    private javax.swing.JMenuItem ItemAgregarPR;
    private javax.swing.JMenuItem ItemCambioPass;
    private javax.swing.JMenuItem ItemEliminarN;
    private javax.swing.JMenuItem ItemEliminarPR;
    private javax.swing.JMenuItem ItemMostrar;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JMenu MenuAdmin;
    private javax.swing.JMenuBar MenuBarAdmin;
    private javax.swing.JMenu MenuN;
    private javax.swing.JMenu MenuPR;
    private javax.swing.JPanel PanelContent;
    private javax.swing.JLabel TituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
