/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaMain;

import Usuarios.Admin;

import javax.swing.*;

public class VentanaAdmin extends javax.swing.JFrame {

    public VentanaAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        Borde = new javax.swing.JPanel();
        ExitButton = new javax.swing.JButton();
        TituloPrincipal = new javax.swing.JLabel();
        TextAdminName = new javax.swing.JLabel();
        TextPass = new javax.swing.JLabel();
        FieldName = new javax.swing.JTextField();
        TextID = new javax.swing.JLabel();
        FieldID = new javax.swing.JTextField();
        FieldPass = new javax.swing.JTextField();
        IngresarButton = new javax.swing.JButton();
        TextErrorAdmin = new javax.swing.JLabel();
        TextErrorID = new javax.swing.JLabel();
        TextErrorPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(201, 234, 253));

        Borde.setBackground(new java.awt.Color(76, 168, 207));

        ExitButton.setBackground(new java.awt.Color(76, 168, 207));
        ExitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Regresar");
        ExitButton.setBorder(null);
        ExitButton.setBorderPainted(false);
        ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitButton.setMinimumSize(new java.awt.Dimension(78, 28));
        ExitButton.setPreferredSize(new java.awt.Dimension(78, 28));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BordeLayout = new javax.swing.GroupLayout(Borde);
        Borde.setLayout(BordeLayout);
        BordeLayout.setHorizontalGroup(
            BordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BordeLayout.createSequentialGroup()
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BordeLayout.setVerticalGroup(
            BordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TituloPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        TituloPrincipal.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        TituloPrincipal.setForeground(new java.awt.Color(0, 0, 102));
        TituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloPrincipal.setText("RecyPoint");
        TituloPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));

        TextAdminName.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextAdminName.setForeground(new java.awt.Color(76, 168, 207));
        TextAdminName.setText("Nombre administrador:");
        TextAdminName.setMaximumSize(new java.awt.Dimension(200, 40));
        TextAdminName.setPreferredSize(new java.awt.Dimension(200, 40));

        TextPass.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextPass.setForeground(new java.awt.Color(76, 168, 207));
        TextPass.setText("Contraseña:");
        TextPass.setMaximumSize(new java.awt.Dimension(100, 40));
        TextPass.setPreferredSize(new java.awt.Dimension(100, 40));

        FieldName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldName.setBorder(null);
        FieldName.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldName.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNameActionPerformed(evt);
            }
        });

        TextID.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextID.setForeground(new java.awt.Color(76, 168, 207));
        TextID.setText("Identificador:");
        TextID.setMaximumSize(new java.awt.Dimension(100, 40));
        TextID.setPreferredSize(new java.awt.Dimension(100, 40));

        FieldID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldID.setBorder(null);
        FieldID.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldID.setPreferredSize(new java.awt.Dimension(140, 35));

        FieldPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldPass.setBorder(null);
        FieldPass.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldPass.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldPassActionPerformed(evt);
            }
        });

        IngresarButton.setBackground(new java.awt.Color(76, 168, 207));
        IngresarButton.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        IngresarButton.setForeground(new java.awt.Color(255, 255, 255));
        IngresarButton.setText("Ingresar");
        IngresarButton.setMaximumSize(new java.awt.Dimension(104, 40));
        IngresarButton.setPreferredSize(new java.awt.Dimension(104, 40));
        IngresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarButtonActionPerformed(evt);
            }
        });

        TextErrorAdmin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TextErrorAdmin.setForeground(new java.awt.Color(255, 0, 0));
        TextErrorAdmin.setText("jLabel1");

        TextErrorID.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TextErrorID.setForeground(new java.awt.Color(255, 0, 0));
        TextErrorID.setText("jLabel2");

        TextErrorPass.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TextErrorPass.setForeground(new java.awt.Color(255, 0, 0));
        TextErrorPass.setText("jLabel3");
        TextErrorPass.setMaximumSize(new java.awt.Dimension(37, 22));
        TextErrorPass.setPreferredSize(new java.awt.Dimension(37, 22));

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Borde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(TituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addComponent(TextPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(FieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TextErrorPass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextAdminName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextErrorAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextErrorID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IngresarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(Borde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextErrorAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextErrorID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextErrorPass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(IngresarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        Principal Exit = new Principal();
        Exit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void IngresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarButtonActionPerformed
        //Condicion con funcion boleana para saber si se encuentran los registros ingresados

        Admin administrador = new Admin();
        String[] data = new String[2];
        data[0] = FieldID.getText();
        data[1] = FieldPass.getText();
        if(administrador.ValidarAdministrador(data)){
            //--> abrir ventana de funcionalidades del administrador JFrame
            AdminFuncion ventanaAdmin = new AdminFuncion();
            ventanaAdmin.setVisible(true);
            this.setVisible(false);
        }else{
            // --> Mostrar un showDialog de que hay datos ingresado incorrectos
            JOptionPane.showMessageDialog(null, "Uno o más datos son incorrectos");
        }


    }//GEN-LAST:event_IngresarButtonActionPerformed

    private void FieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNameActionPerformed

    private void FieldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Borde;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField FieldID;
    private javax.swing.JTextField FieldName;
    private javax.swing.JTextField FieldPass;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton IngresarButton;
    private javax.swing.JLabel TextAdminName;
    private javax.swing.JLabel TextErrorAdmin;
    private javax.swing.JLabel TextErrorID;
    private javax.swing.JLabel TextErrorPass;
    private javax.swing.JLabel TextID;
    private javax.swing.JLabel TextPass;
    private javax.swing.JLabel TituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
