/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistasAdministrador;

import Manejo_Csv.CSVFile;
import VistaMain.AdminFuncion;

import javax.swing.*;
import java.awt.*;

public class CambiarPassword extends javax.swing.JPanel {

    public CambiarPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCambioPass = new javax.swing.JPanel();
        TextID = new javax.swing.JLabel();
        TextPassNew = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        FieldID = new javax.swing.JTextField();
        FieldPassNew = new javax.swing.JTextField();
        CambiarButton = new javax.swing.JButton();
        TextPassActual = new javax.swing.JLabel();
        FielPassActual = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelCambioPass.setBackground(new java.awt.Color(201, 234, 253));
        PanelCambioPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextID.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextID.setForeground(new java.awt.Color(76, 168, 207));
        TextID.setText("Identificador:");
        TextID.setMaximumSize(new java.awt.Dimension(100, 40));
        TextID.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelCambioPass.add(TextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        TextPassNew.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextPassNew.setForeground(new java.awt.Color(76, 168, 207));
        TextPassNew.setText("Contraseña nueva:");
        TextPassNew.setMaximumSize(new java.awt.Dimension(100, 40));
        TextPassNew.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelCambioPass.add(TextPassNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 150, -1));

        jPanel2.setBackground(new java.awt.Color(76, 168, 207));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 51));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Cambio de contraseña");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        PanelCambioPass.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        PanelCambioPass.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 500, 5));

        FieldID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldID.setBorder(null);
        FieldID.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldID.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldIDActionPerformed(evt);
            }
        });
        PanelCambioPass.add(FieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, 30));

        FieldPassNew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldPassNew.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldPassNew.setBorder(null);
        FieldPassNew.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldPassNew.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldPassNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldPassNewActionPerformed(evt);
            }
        });
        PanelCambioPass.add(FieldPassNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, 30));

        CambiarButton.setBackground(new java.awt.Color(76, 168, 207));
        CambiarButton.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        CambiarButton.setForeground(new java.awt.Color(255, 255, 255));
        CambiarButton.setText("Cambiar");
        CambiarButton.setMaximumSize(new java.awt.Dimension(104, 40));
        CambiarButton.setPreferredSize(new java.awt.Dimension(104, 40));
        CambiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarButtonActionPerformed(evt);
            }
        });
        PanelCambioPass.add(CambiarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        TextPassActual.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextPassActual.setForeground(new java.awt.Color(76, 168, 207));
        TextPassActual.setText("Contraseña actual:");
        TextPassActual.setMaximumSize(new java.awt.Dimension(100, 40));
        TextPassActual.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelCambioPass.add(TextPassActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, -1));

        FielPassActual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FielPassActual.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FielPassActual.setBorder(null);
        FielPassActual.setMaximumSize(new java.awt.Dimension(140, 35));
        FielPassActual.setPreferredSize(new java.awt.Dimension(140, 35));
        FielPassActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FielPassActualActionPerformed(evt);
            }
        });
        PanelCambioPass.add(FielPassActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, 30));

        add(PanelCambioPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void CambiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarButtonActionPerformed
         //VALIDAR QUE SE HAYAN INGRESADO BIEN LOS DATOS --> Funciones de la clase
         if (ValidarCampos()){
            System.out.println("SE VALIDARON TODOS LOS CAMPOS PARA CAMBIAR LA CONTRASEÑA");
             if (comprobarAdmin(FieldID.getText(), FielPassActual.getText()) ) {
                 System.out.println("EL ADMINISTRADOR EXISTE!");
                 CambiarContraseniaCSV(FieldID.getText(), FieldPassNew.getText());
                 System.out.println("SE VALIDÓ EL ADMINISTRADOR PARA CAMBIAR LA CONTRASEÑA");
                 JOptionPane.showMessageDialog(null, "Se cambió la contraseña con éxito");

                 new AdminFuncion().setVisible(true);
                 JComponent comp = (JComponent) evt.getSource();
                 Window win = SwingUtilities.getWindowAncestor(comp);
                 win.dispose();
             }
        }
    }//GEN-LAST:event_CambiarButtonActionPerformed
    public boolean ValidarCampos() {
        //MODIFICAR RETROALIMENTACIÓN !!!!
        String identificador = FieldID.getText();
        String contraseniaActual = FielPassActual.getText();
        String contraseniaNueva = FieldPassNew.getText();

        if(!identificador.matches("[0-9]*+")){
            JOptionPane.showMessageDialog(null,"ERROR: El campo Identificador permite sólo numeros");
            return false;
        }

        if(!contraseniaActual.matches("([a-zA-Z]*+[0-9]*)+")){
            JOptionPane.showMessageDialog(null,"ERROR: El campo contraseña Actual permite sólo letras y números");
            return false;
        }
        if(!contraseniaNueva.matches("([a-zA-Z]*+[0-9]*)+")){
            JOptionPane.showMessageDialog(null,"ERROR: El campo Contraseña Nueva permite sólo letras y números");
            return false;
        }
        return true;
    }

    public boolean comprobarAdmin(String identificador, String contraseniaActual) {
        //buscar en csv que el id y la contraseña existan.
        try {
            CSVFile admin = new CSVFile();
            if (admin.comprobarAdminCSV("src/main/resources/administrador/CSVadmin.csv", identificador, contraseniaActual)){
                return true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            return false;
        }
        return false;
    }

    public void CambiarContraseniaCSV(String identificador, String nuevaContrasenia) {
        System.out.println("CAMBIANDO CONTRASEÑA...");
        //cambiar contraseña por id desde el CSV.
    }

    private void FieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldIDActionPerformed

    private void FieldPassNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPassNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPassNewActionPerformed

    private void FielPassActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FielPassActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FielPassActualActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambiarButton;
    private javax.swing.JTextField FielPassActual;
    private javax.swing.JTextField FieldID;
    private javax.swing.JTextField FieldPassNew;
    private javax.swing.JPanel PanelCambioPass;
    private javax.swing.JLabel TextID;
    private javax.swing.JLabel TextPassActual;
    private javax.swing.JLabel TextPassNew;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
