/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistasPuntosR;
import VistaMain.AdminFuncion;
/**
 *
 * @author Byron
 */
public class ActualizarPR1 extends javax.swing.JPanel {

    /**
     * Creates new form ActualizarPR
     */
    public ActualizarPR1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelActualizarPR = new javax.swing.JPanel();
        PanelTitulo = new javax.swing.JPanel();
        Titulo2 = new javax.swing.JLabel();
        Borde = new javax.swing.JPanel();
        BuscarButton = new javax.swing.JButton();
        LabelID = new javax.swing.JLabel();
        FieldIdentificador = new javax.swing.JTextField();

        PanelActualizarPR.setBackground(new java.awt.Color(201, 234, 253));
        PanelActualizarPR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelTitulo.setBackground(new java.awt.Color(76, 168, 207));

        Titulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(0, 0, 51));
        Titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo2.setText("Actualizar punto de reciclaje");

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(Titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        PanelActualizarPR.add(PanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        Borde.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout BordeLayout = new javax.swing.GroupLayout(Borde);
        Borde.setLayout(BordeLayout);
        BordeLayout.setHorizontalGroup(
            BordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        BordeLayout.setVerticalGroup(
            BordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        PanelActualizarPR.add(Borde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 500, 5));

        BuscarButton.setBackground(new java.awt.Color(76, 168, 207));
        BuscarButton.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BuscarButton.setForeground(new java.awt.Color(255, 255, 255));
        BuscarButton.setText("Buscar");
        BuscarButton.setMaximumSize(new java.awt.Dimension(104, 40));
        BuscarButton.setPreferredSize(new java.awt.Dimension(104, 40));
        BuscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarButtonActionPerformed(evt);
            }
        });
        PanelActualizarPR.add(BuscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        LabelID.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        LabelID.setForeground(new java.awt.Color(76, 168, 207));
        LabelID.setText("Identificador punto de reciclaje:");
        LabelID.setMaximumSize(new java.awt.Dimension(100, 40));
        LabelID.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelActualizarPR.add(LabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 250, -1));

        FieldIdentificador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldIdentificador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldIdentificador.setBorder(null);
        FieldIdentificador.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldIdentificador.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldIdentificadorActionPerformed(evt);
            }
        });
        PanelActualizarPR.add(FieldIdentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelActualizarPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelActualizarPR, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarButtonActionPerformed
        /*
        VALIDAR QUE SE HAYAN INGRESADO BIEN LOS DATOS --> Funciones de la clase
        */
        AdminFuncion auxFuncion = new AdminFuncion();
        ActualizarPR2 updatePR = new ActualizarPR2();
        auxFuncion.MostrarPanel(updatePR);
    }//GEN-LAST:event_BuscarButtonActionPerformed

    private void FieldIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldIdentificadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Borde;
    private javax.swing.JButton BuscarButton;
    private javax.swing.JTextField FieldIdentificador;
    private javax.swing.JLabel LabelID;
    private javax.swing.JPanel PanelActualizarPR;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JLabel Titulo2;
    // End of variables declaration//GEN-END:variables
}
