/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistasPuntosR;

/**
 *
 * @author Byron
 */
public class AgregarPR extends javax.swing.JPanel {

    /**
     * Creates new form Agregar
     */
    public AgregarPR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAgregarPR = new javax.swing.JPanel();
        LabelCiudad = new javax.swing.JLabel();
        LabelPeriodoV = new javax.swing.JLabel();
        LabelTReciclaje = new javax.swing.JLabel();
        LabelDireccion = new javax.swing.JLabel();
        PanelTitulo = new javax.swing.JPanel();
        Titulo2 = new javax.swing.JLabel();
        Borde = new javax.swing.JPanel();
        FieldDireccion = new javax.swing.JTextField();
        FieldVaciado = new javax.swing.JTextField();
        FieldTReciclaje = new javax.swing.JTextField();
        FieldCiudad = new javax.swing.JTextField();
        AgregarButton = new javax.swing.JButton();
        LabelErrorID = new javax.swing.JLabel();
        LabelErrorDireccion = new javax.swing.JLabel();
        LabelErrorTR = new javax.swing.JLabel();
        LabelErrorCiudad = new javax.swing.JLabel();
        LabelCapacidad2 = new javax.swing.JLabel();
        LabelCapacidad1 = new javax.swing.JLabel();
        LabelID = new javax.swing.JLabel();
        LabelCapacidad4 = new javax.swing.JLabel();
        FieldCapacidad1 = new javax.swing.JTextField();
        FieldIdentificador = new javax.swing.JTextField();
        LabelErrorCapacidad1 = new javax.swing.JLabel();

        PanelAgregarPR.setBackground(new java.awt.Color(201, 234, 253));
        PanelAgregarPR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelCiudad.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        LabelCiudad.setForeground(new java.awt.Color(76, 168, 207));
        LabelCiudad.setText("Ciudad:");
        LabelCiudad.setMaximumSize(new java.awt.Dimension(100, 40));
        LabelCiudad.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelAgregarPR.add(LabelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, -1));

        LabelPeriodoV.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        LabelPeriodoV.setForeground(new java.awt.Color(76, 168, 207));
        LabelPeriodoV.setText("Periodo vaciado:");
        LabelPeriodoV.setMaximumSize(new java.awt.Dimension(100, 40));
        LabelPeriodoV.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelAgregarPR.add(LabelPeriodoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 140, -1));

        LabelTReciclaje.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        LabelTReciclaje.setForeground(new java.awt.Color(76, 168, 207));
        LabelTReciclaje.setText("Tipo de reciclaje:");
        LabelTReciclaje.setMaximumSize(new java.awt.Dimension(100, 40));
        LabelTReciclaje.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelAgregarPR.add(LabelTReciclaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, -1));

        LabelDireccion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        LabelDireccion.setForeground(new java.awt.Color(76, 168, 207));
        LabelDireccion.setText("Dirección:");
        LabelDireccion.setMaximumSize(new java.awt.Dimension(100, 40));
        LabelDireccion.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelAgregarPR.add(LabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, -1));

        PanelTitulo.setBackground(new java.awt.Color(76, 168, 207));

        Titulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(0, 0, 51));
        Titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo2.setText("Agregar punto de reciclaje");

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(Titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        PanelAgregarPR.add(PanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        Borde.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout BordeLayout = new javax.swing.GroupLayout(Borde);
        Borde.setLayout(BordeLayout);
        BordeLayout.setHorizontalGroup(
            BordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        BordeLayout.setVerticalGroup(
            BordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        PanelAgregarPR.add(Borde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 500, 5));

        FieldDireccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldDireccion.setBorder(null);
        FieldDireccion.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldDireccion.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldDireccionActionPerformed(evt);
            }
        });
        PanelAgregarPR.add(FieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, 30));

        FieldVaciado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldVaciado.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldVaciado.setBorder(null);
        FieldVaciado.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldVaciado.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldVaciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldVaciadoActionPerformed(evt);
            }
        });
        PanelAgregarPR.add(FieldVaciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, 30));

        FieldTReciclaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldTReciclaje.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldTReciclaje.setBorder(null);
        FieldTReciclaje.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldTReciclaje.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldTReciclaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldTReciclajeActionPerformed(evt);
            }
        });
        PanelAgregarPR.add(FieldTReciclaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, 30));

        FieldCiudad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldCiudad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldCiudad.setBorder(null);
        FieldCiudad.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldCiudad.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCiudadActionPerformed(evt);
            }
        });
        PanelAgregarPR.add(FieldCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, 30));

        AgregarButton.setBackground(new java.awt.Color(76, 168, 207));
        AgregarButton.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        AgregarButton.setForeground(new java.awt.Color(255, 255, 255));
        AgregarButton.setText("Agregar");
        AgregarButton.setMaximumSize(new java.awt.Dimension(104, 40));
        AgregarButton.setPreferredSize(new java.awt.Dimension(104, 40));
        AgregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarButtonActionPerformed(evt);
            }
        });
        PanelAgregarPR.add(AgregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        LabelErrorID.setForeground(new java.awt.Color(255, 0, 0));
        LabelErrorID.setText("jLabel1");
        PanelAgregarPR.add(LabelErrorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 170, 20));

        LabelErrorDireccion.setForeground(new java.awt.Color(255, 0, 0));
        LabelErrorDireccion.setText("jLabel1");
        PanelAgregarPR.add(LabelErrorDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 86, 170, 20));

        LabelErrorTR.setForeground(new java.awt.Color(255, 0, 0));
        LabelErrorTR.setText("jLabel1");
        PanelAgregarPR.add(LabelErrorTR, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 170, 20));

        LabelErrorCiudad.setForeground(new java.awt.Color(255, 0, 0));
        LabelErrorCiudad.setText("jLabel1");
        PanelAgregarPR.add(LabelErrorCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 170, 20));

        LabelCapacidad2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelCapacidad2.setForeground(new java.awt.Color(76, 168, 207));
        LabelCapacidad2.setText("(en dias)");
        PanelAgregarPR.add(LabelCapacidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        LabelCapacidad1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        LabelCapacidad1.setForeground(new java.awt.Color(76, 168, 207));
        LabelCapacidad1.setText("Capacidad de carga:");
        LabelCapacidad1.setMaximumSize(new java.awt.Dimension(100, 40));
        LabelCapacidad1.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelAgregarPR.add(LabelCapacidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, -1));

        LabelID.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        LabelID.setForeground(new java.awt.Color(76, 168, 207));
        LabelID.setText("Identificador:");
        LabelID.setMaximumSize(new java.awt.Dimension(100, 40));
        LabelID.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelAgregarPR.add(LabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, -1));

        LabelCapacidad4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelCapacidad4.setForeground(new java.awt.Color(76, 168, 207));
        LabelCapacidad4.setText("(en kilogramos)");
        PanelAgregarPR.add(LabelCapacidad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        FieldCapacidad1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldCapacidad1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldCapacidad1.setBorder(null);
        FieldCapacidad1.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldCapacidad1.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldCapacidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCapacidad1ActionPerformed(evt);
            }
        });
        PanelAgregarPR.add(FieldCapacidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 30));

        FieldIdentificador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FieldIdentificador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldIdentificador.setBorder(null);
        FieldIdentificador.setMaximumSize(new java.awt.Dimension(140, 35));
        FieldIdentificador.setPreferredSize(new java.awt.Dimension(140, 35));
        FieldIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldIdentificadorActionPerformed(evt);
            }
        });
        PanelAgregarPR.add(FieldIdentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, 30));

        LabelErrorCapacidad1.setForeground(new java.awt.Color(255, 0, 0));
        LabelErrorCapacidad1.setText("jLabel1");
        PanelAgregarPR.add(LabelErrorCapacidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 170, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelAgregarPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelAgregarPR, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldDireccionActionPerformed

    private void FieldVaciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldVaciadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldVaciadoActionPerformed

    private void FieldTReciclajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldTReciclajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldTReciclajeActionPerformed

    private void FieldCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCiudadActionPerformed

    private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed
        /*
        VALIDAR QUE SE HAYAN INGRESADO BIEN LOS DATOS --> Funciones de la clase
        */
    }//GEN-LAST:event_AgregarButtonActionPerformed

    private void FieldCapacidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCapacidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCapacidad1ActionPerformed

    private void FieldIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldIdentificadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarButton;
    private javax.swing.JPanel Borde;
    private javax.swing.JTextField FieldCapacidad1;
    private javax.swing.JTextField FieldCiudad;
    private javax.swing.JTextField FieldDireccion;
    private javax.swing.JTextField FieldIdentificador;
    private javax.swing.JTextField FieldTReciclaje;
    private javax.swing.JTextField FieldVaciado;
    private javax.swing.JLabel LabelCapacidad1;
    private javax.swing.JLabel LabelCapacidad2;
    private javax.swing.JLabel LabelCapacidad4;
    private javax.swing.JLabel LabelCiudad;
    private javax.swing.JLabel LabelDireccion;
    private javax.swing.JLabel LabelErrorCapacidad1;
    private javax.swing.JLabel LabelErrorCiudad;
    private javax.swing.JLabel LabelErrorDireccion;
    private javax.swing.JLabel LabelErrorID;
    private javax.swing.JLabel LabelErrorTR;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelPeriodoV;
    private javax.swing.JLabel LabelTReciclaje;
    private javax.swing.JPanel PanelAgregarPR;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JLabel Titulo2;
    // End of variables declaration//GEN-END:variables
}
